listeners.tcp.default = 5672

mqtt.listeners.tcp.default = 1883
mqtt.allow_anonymous = false
mqtt.vhost = /
mqtt.exchange = amq.topic
mqtt.prefetch = 10

definitions.import_backend = local_filesystem
definitions.local.path = /etc/rabbitmq/definitions.json
definitions.skip_if_unchanged = true

management.tcp.port = 15672
prometheus.tcp.port = 15692

log.console = true
log.console.level = info
